<?php
/**
 * InlineResponse200
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ProviEmplea API
 *
 * API REST para la plataforma de empleo ProviEmplea de Providencia. Permite gestionar talentos, empresas y procesos de selección con curriculum ciego.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.81
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * InlineResponse200 Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse200 implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'inline_response_200';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'total_personas' => 'int',
        'personas_validadas' => 'int',
        'total_empresas' => 'int',
        'empresas_validadas' => 'int',
        'contactos_pendientes' => 'int',
        'contactos_en_proceso' => 'int',
        'contactos_exitosos' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'total_personas' => null,
        'personas_validadas' => null,
        'total_empresas' => null,
        'empresas_validadas' => null,
        'contactos_pendientes' => null,
        'contactos_en_proceso' => null,
        'contactos_exitosos' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'total_personas' => 'total_personas',
        'personas_validadas' => 'personas_validadas',
        'total_empresas' => 'total_empresas',
        'empresas_validadas' => 'empresas_validadas',
        'contactos_pendientes' => 'contactos_pendientes',
        'contactos_en_proceso' => 'contactos_en_proceso',
        'contactos_exitosos' => 'contactos_exitosos'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'total_personas' => 'setTotalPersonas',
        'personas_validadas' => 'setPersonasValidadas',
        'total_empresas' => 'setTotalEmpresas',
        'empresas_validadas' => 'setEmpresasValidadas',
        'contactos_pendientes' => 'setContactosPendientes',
        'contactos_en_proceso' => 'setContactosEnProceso',
        'contactos_exitosos' => 'setContactosExitosos'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'total_personas' => 'getTotalPersonas',
        'personas_validadas' => 'getPersonasValidadas',
        'total_empresas' => 'getTotalEmpresas',
        'empresas_validadas' => 'getEmpresasValidadas',
        'contactos_pendientes' => 'getContactosPendientes',
        'contactos_en_proceso' => 'getContactosEnProceso',
        'contactos_exitosos' => 'getContactosExitosos'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['total_personas'] = isset($data['total_personas']) ? $data['total_personas'] : null;
        $this->container['personas_validadas'] = isset($data['personas_validadas']) ? $data['personas_validadas'] : null;
        $this->container['total_empresas'] = isset($data['total_empresas']) ? $data['total_empresas'] : null;
        $this->container['empresas_validadas'] = isset($data['empresas_validadas']) ? $data['empresas_validadas'] : null;
        $this->container['contactos_pendientes'] = isset($data['contactos_pendientes']) ? $data['contactos_pendientes'] : null;
        $this->container['contactos_en_proceso'] = isset($data['contactos_en_proceso']) ? $data['contactos_en_proceso'] : null;
        $this->container['contactos_exitosos'] = isset($data['contactos_exitosos']) ? $data['contactos_exitosos'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets total_personas
     *
     * @return int
     */
    public function getTotalPersonas()
    {
        return $this->container['total_personas'];
    }

    /**
     * Sets total_personas
     *
     * @param int $total_personas total_personas
     *
     * @return $this
     */
    public function setTotalPersonas($total_personas)
    {
        $this->container['total_personas'] = $total_personas;

        return $this;
    }

    /**
     * Gets personas_validadas
     *
     * @return int
     */
    public function getPersonasValidadas()
    {
        return $this->container['personas_validadas'];
    }

    /**
     * Sets personas_validadas
     *
     * @param int $personas_validadas personas_validadas
     *
     * @return $this
     */
    public function setPersonasValidadas($personas_validadas)
    {
        $this->container['personas_validadas'] = $personas_validadas;

        return $this;
    }

    /**
     * Gets total_empresas
     *
     * @return int
     */
    public function getTotalEmpresas()
    {
        return $this->container['total_empresas'];
    }

    /**
     * Sets total_empresas
     *
     * @param int $total_empresas total_empresas
     *
     * @return $this
     */
    public function setTotalEmpresas($total_empresas)
    {
        $this->container['total_empresas'] = $total_empresas;

        return $this;
    }

    /**
     * Gets empresas_validadas
     *
     * @return int
     */
    public function getEmpresasValidadas()
    {
        return $this->container['empresas_validadas'];
    }

    /**
     * Sets empresas_validadas
     *
     * @param int $empresas_validadas empresas_validadas
     *
     * @return $this
     */
    public function setEmpresasValidadas($empresas_validadas)
    {
        $this->container['empresas_validadas'] = $empresas_validadas;

        return $this;
    }

    /**
     * Gets contactos_pendientes
     *
     * @return int
     */
    public function getContactosPendientes()
    {
        return $this->container['contactos_pendientes'];
    }

    /**
     * Sets contactos_pendientes
     *
     * @param int $contactos_pendientes contactos_pendientes
     *
     * @return $this
     */
    public function setContactosPendientes($contactos_pendientes)
    {
        $this->container['contactos_pendientes'] = $contactos_pendientes;

        return $this;
    }

    /**
     * Gets contactos_en_proceso
     *
     * @return int
     */
    public function getContactosEnProceso()
    {
        return $this->container['contactos_en_proceso'];
    }

    /**
     * Sets contactos_en_proceso
     *
     * @param int $contactos_en_proceso contactos_en_proceso
     *
     * @return $this
     */
    public function setContactosEnProceso($contactos_en_proceso)
    {
        $this->container['contactos_en_proceso'] = $contactos_en_proceso;

        return $this;
    }

    /**
     * Gets contactos_exitosos
     *
     * @return int
     */
    public function getContactosExitosos()
    {
        return $this->container['contactos_exitosos'];
    }

    /**
     * Sets contactos_exitosos
     *
     * @param int $contactos_exitosos contactos_exitosos
     *
     * @return $this
     */
    public function setContactosExitosos($contactos_exitosos)
    {
        $this->container['contactos_exitosos'] = $contactos_exitosos;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
