<?php
/**
 * PersonaCVCiego
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ProviEmplea API
 *
 * API REST para la plataforma de empleo ProviEmplea de Providencia. Permite gestionar talentos, empresas y procesos de selección con curriculum ciego.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.81
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * PersonaCVCiego Class Doc Comment
 *
 * @category Class
 * @description Vista pública del talento sin datos personales identificables
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PersonaCVCiego implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'PersonaCVCiego';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'string',
        'codigo_talento' => 'string',
        'resumen' => 'string',
        'nivel_educacional' => 'string',
        'titulo_carrera' => 'string',
        'anio_egreso' => 'int',
        'anios_experiencia' => 'int',
        'tipo_jornada' => 'string',
        'modalidad' => 'string',
        'persona_discapacidad' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => 'uuid',
        'codigo_talento' => null,
        'resumen' => null,
        'nivel_educacional' => null,
        'titulo_carrera' => null,
        'anio_egreso' => null,
        'anios_experiencia' => null,
        'tipo_jornada' => null,
        'modalidad' => null,
        'persona_discapacidad' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'codigo_talento' => 'codigo_talento',
        'resumen' => 'resumen',
        'nivel_educacional' => 'nivel_educacional',
        'titulo_carrera' => 'titulo_carrera',
        'anio_egreso' => 'anio_egreso',
        'anios_experiencia' => 'anios_experiencia',
        'tipo_jornada' => 'tipo_jornada',
        'modalidad' => 'modalidad',
        'persona_discapacidad' => 'persona_discapacidad'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'codigo_talento' => 'setCodigoTalento',
        'resumen' => 'setResumen',
        'nivel_educacional' => 'setNivelEducacional',
        'titulo_carrera' => 'setTituloCarrera',
        'anio_egreso' => 'setAnioEgreso',
        'anios_experiencia' => 'setAniosExperiencia',
        'tipo_jornada' => 'setTipoJornada',
        'modalidad' => 'setModalidad',
        'persona_discapacidad' => 'setPersonaDiscapacidad'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'codigo_talento' => 'getCodigoTalento',
        'resumen' => 'getResumen',
        'nivel_educacional' => 'getNivelEducacional',
        'titulo_carrera' => 'getTituloCarrera',
        'anio_egreso' => 'getAnioEgreso',
        'anios_experiencia' => 'getAniosExperiencia',
        'tipo_jornada' => 'getTipoJornada',
        'modalidad' => 'getModalidad',
        'persona_discapacidad' => 'getPersonaDiscapacidad'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['codigo_talento'] = isset($data['codigo_talento']) ? $data['codigo_talento'] : null;
        $this->container['resumen'] = isset($data['resumen']) ? $data['resumen'] : null;
        $this->container['nivel_educacional'] = isset($data['nivel_educacional']) ? $data['nivel_educacional'] : null;
        $this->container['titulo_carrera'] = isset($data['titulo_carrera']) ? $data['titulo_carrera'] : null;
        $this->container['anio_egreso'] = isset($data['anio_egreso']) ? $data['anio_egreso'] : null;
        $this->container['anios_experiencia'] = isset($data['anios_experiencia']) ? $data['anios_experiencia'] : null;
        $this->container['tipo_jornada'] = isset($data['tipo_jornada']) ? $data['tipo_jornada'] : null;
        $this->container['modalidad'] = isset($data['modalidad']) ? $data['modalidad'] : null;
        $this->container['persona_discapacidad'] = isset($data['persona_discapacidad']) ? $data['persona_discapacidad'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets codigo_talento
     *
     * @return string
     */
    public function getCodigoTalento()
    {
        return $this->container['codigo_talento'];
    }

    /**
     * Sets codigo_talento
     *
     * @param string $codigo_talento codigo_talento
     *
     * @return $this
     */
    public function setCodigoTalento($codigo_talento)
    {
        $this->container['codigo_talento'] = $codigo_talento;

        return $this;
    }

    /**
     * Gets resumen
     *
     * @return string
     */
    public function getResumen()
    {
        return $this->container['resumen'];
    }

    /**
     * Sets resumen
     *
     * @param string $resumen resumen
     *
     * @return $this
     */
    public function setResumen($resumen)
    {
        $this->container['resumen'] = $resumen;

        return $this;
    }

    /**
     * Gets nivel_educacional
     *
     * @return string
     */
    public function getNivelEducacional()
    {
        return $this->container['nivel_educacional'];
    }

    /**
     * Sets nivel_educacional
     *
     * @param string $nivel_educacional nivel_educacional
     *
     * @return $this
     */
    public function setNivelEducacional($nivel_educacional)
    {
        $this->container['nivel_educacional'] = $nivel_educacional;

        return $this;
    }

    /**
     * Gets titulo_carrera
     *
     * @return string
     */
    public function getTituloCarrera()
    {
        return $this->container['titulo_carrera'];
    }

    /**
     * Sets titulo_carrera
     *
     * @param string $titulo_carrera titulo_carrera
     *
     * @return $this
     */
    public function setTituloCarrera($titulo_carrera)
    {
        $this->container['titulo_carrera'] = $titulo_carrera;

        return $this;
    }

    /**
     * Gets anio_egreso
     *
     * @return int
     */
    public function getAnioEgreso()
    {
        return $this->container['anio_egreso'];
    }

    /**
     * Sets anio_egreso
     *
     * @param int $anio_egreso anio_egreso
     *
     * @return $this
     */
    public function setAnioEgreso($anio_egreso)
    {
        $this->container['anio_egreso'] = $anio_egreso;

        return $this;
    }

    /**
     * Gets anios_experiencia
     *
     * @return int
     */
    public function getAniosExperiencia()
    {
        return $this->container['anios_experiencia'];
    }

    /**
     * Sets anios_experiencia
     *
     * @param int $anios_experiencia anios_experiencia
     *
     * @return $this
     */
    public function setAniosExperiencia($anios_experiencia)
    {
        $this->container['anios_experiencia'] = $anios_experiencia;

        return $this;
    }

    /**
     * Gets tipo_jornada
     *
     * @return string
     */
    public function getTipoJornada()
    {
        return $this->container['tipo_jornada'];
    }

    /**
     * Sets tipo_jornada
     *
     * @param string $tipo_jornada tipo_jornada
     *
     * @return $this
     */
    public function setTipoJornada($tipo_jornada)
    {
        $this->container['tipo_jornada'] = $tipo_jornada;

        return $this;
    }

    /**
     * Gets modalidad
     *
     * @return string
     */
    public function getModalidad()
    {
        return $this->container['modalidad'];
    }

    /**
     * Sets modalidad
     *
     * @param string $modalidad modalidad
     *
     * @return $this
     */
    public function setModalidad($modalidad)
    {
        $this->container['modalidad'] = $modalidad;

        return $this;
    }

    /**
     * Gets persona_discapacidad
     *
     * @return bool
     */
    public function getPersonaDiscapacidad()
    {
        return $this->container['persona_discapacidad'];
    }

    /**
     * Sets persona_discapacidad
     *
     * @param bool $persona_discapacidad persona_discapacidad
     *
     * @return $this
     */
    public function setPersonaDiscapacidad($persona_discapacidad)
    {
        $this->container['persona_discapacidad'] = $persona_discapacidad;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
