<?php
/**
 * PersonaInput
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ProviEmplea API
 *
 * API REST para la plataforma de empleo ProviEmplea de Providencia. Permite gestionar talentos, empresas y procesos de selección con curriculum ciego.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.81
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * PersonaInput Class Doc Comment
 *
 * @category Class
 * @description Datos para crear o actualizar una persona
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PersonaInput implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'PersonaInput';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'email' => 'string',
        'telefono' => 'string',
        'resumen' => 'string',
        'nivel_educacional' => 'string',
        'titulo_carrera' => 'string',
        'anio_egreso' => 'int',
        'anios_experiencia' => 'int',
        'areas_experiencia' => 'string[]',
        'competencias' => 'string[]',
        'rango_renta' => 'string',
        'tipo_jornada' => 'string',
        'modalidad' => 'string',
        'persona_discapacidad' => 'bool',
        'portafolio_url' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'email' => 'email',
        'telefono' => null,
        'resumen' => null,
        'nivel_educacional' => null,
        'titulo_carrera' => null,
        'anio_egreso' => null,
        'anios_experiencia' => null,
        'areas_experiencia' => null,
        'competencias' => null,
        'rango_renta' => null,
        'tipo_jornada' => null,
        'modalidad' => null,
        'persona_discapacidad' => null,
        'portafolio_url' => 'url'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'email' => 'email',
        'telefono' => 'telefono',
        'resumen' => 'resumen',
        'nivel_educacional' => 'nivel_educacional',
        'titulo_carrera' => 'titulo_carrera',
        'anio_egreso' => 'anio_egreso',
        'anios_experiencia' => 'anios_experiencia',
        'areas_experiencia' => 'areas_experiencia',
        'competencias' => 'competencias',
        'rango_renta' => 'rango_renta',
        'tipo_jornada' => 'tipo_jornada',
        'modalidad' => 'modalidad',
        'persona_discapacidad' => 'persona_discapacidad',
        'portafolio_url' => 'portafolio_url'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'email' => 'setEmail',
        'telefono' => 'setTelefono',
        'resumen' => 'setResumen',
        'nivel_educacional' => 'setNivelEducacional',
        'titulo_carrera' => 'setTituloCarrera',
        'anio_egreso' => 'setAnioEgreso',
        'anios_experiencia' => 'setAniosExperiencia',
        'areas_experiencia' => 'setAreasExperiencia',
        'competencias' => 'setCompetencias',
        'rango_renta' => 'setRangoRenta',
        'tipo_jornada' => 'setTipoJornada',
        'modalidad' => 'setModalidad',
        'persona_discapacidad' => 'setPersonaDiscapacidad',
        'portafolio_url' => 'setPortafolioUrl'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'email' => 'getEmail',
        'telefono' => 'getTelefono',
        'resumen' => 'getResumen',
        'nivel_educacional' => 'getNivelEducacional',
        'titulo_carrera' => 'getTituloCarrera',
        'anio_egreso' => 'getAnioEgreso',
        'anios_experiencia' => 'getAniosExperiencia',
        'areas_experiencia' => 'getAreasExperiencia',
        'competencias' => 'getCompetencias',
        'rango_renta' => 'getRangoRenta',
        'tipo_jornada' => 'getTipoJornada',
        'modalidad' => 'getModalidad',
        'persona_discapacidad' => 'getPersonaDiscapacidad',
        'portafolio_url' => 'getPortafolioUrl'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const NIVEL_EDUCACIONAL_BASICA = 'basica';
    const NIVEL_EDUCACIONAL_MEDIA = 'media';
    const NIVEL_EDUCACIONAL_TECNICA = 'tecnica';
    const NIVEL_EDUCACIONAL_UNIVERSITARIA = 'universitaria';
    const NIVEL_EDUCACIONAL_POSTGRADO = 'postgrado';
    const TIPO_JORNADA_COMPLETA = 'completa';
    const TIPO_JORNADA_PART_TIME = 'part-time';
    const TIPO_JORNADA_POR_HORAS = 'por-horas';
    const MODALIDAD_PRESENCIAL = 'presencial';
    const MODALIDAD_REMOTO = 'remoto';
    const MODALIDAD_HIBRIDO = 'hibrido';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getNivelEducacionalAllowableValues()
    {
        return [
            self::NIVEL_EDUCACIONAL_BASICA,
            self::NIVEL_EDUCACIONAL_MEDIA,
            self::NIVEL_EDUCACIONAL_TECNICA,
            self::NIVEL_EDUCACIONAL_UNIVERSITARIA,
            self::NIVEL_EDUCACIONAL_POSTGRADO,
        ];
    }
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTipoJornadaAllowableValues()
    {
        return [
            self::TIPO_JORNADA_COMPLETA,
            self::TIPO_JORNADA_PART_TIME,
            self::TIPO_JORNADA_POR_HORAS,
        ];
    }
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getModalidadAllowableValues()
    {
        return [
            self::MODALIDAD_PRESENCIAL,
            self::MODALIDAD_REMOTO,
            self::MODALIDAD_HIBRIDO,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['email'] = isset($data['email']) ? $data['email'] : null;
        $this->container['telefono'] = isset($data['telefono']) ? $data['telefono'] : null;
        $this->container['resumen'] = isset($data['resumen']) ? $data['resumen'] : null;
        $this->container['nivel_educacional'] = isset($data['nivel_educacional']) ? $data['nivel_educacional'] : null;
        $this->container['titulo_carrera'] = isset($data['titulo_carrera']) ? $data['titulo_carrera'] : null;
        $this->container['anio_egreso'] = isset($data['anio_egreso']) ? $data['anio_egreso'] : null;
        $this->container['anios_experiencia'] = isset($data['anios_experiencia']) ? $data['anios_experiencia'] : null;
        $this->container['areas_experiencia'] = isset($data['areas_experiencia']) ? $data['areas_experiencia'] : null;
        $this->container['competencias'] = isset($data['competencias']) ? $data['competencias'] : null;
        $this->container['rango_renta'] = isset($data['rango_renta']) ? $data['rango_renta'] : null;
        $this->container['tipo_jornada'] = isset($data['tipo_jornada']) ? $data['tipo_jornada'] : null;
        $this->container['modalidad'] = isset($data['modalidad']) ? $data['modalidad'] : null;
        $this->container['persona_discapacidad'] = isset($data['persona_discapacidad']) ? $data['persona_discapacidad'] : null;
        $this->container['portafolio_url'] = isset($data['portafolio_url']) ? $data['portafolio_url'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['email'] === null) {
            $invalidProperties[] = "'email' can't be null";
        }
        $allowedValues = $this->getNivelEducacionalAllowableValues();
        if (!is_null($this->container['nivel_educacional']) && !in_array($this->container['nivel_educacional'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'nivel_educacional', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getTipoJornadaAllowableValues();
        if (!is_null($this->container['tipo_jornada']) && !in_array($this->container['tipo_jornada'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'tipo_jornada', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getModalidadAllowableValues();
        if (!is_null($this->container['modalidad']) && !in_array($this->container['modalidad'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'modalidad', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string $email email
     *
     * @return $this
     */
    public function setEmail($email)
    {
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets telefono
     *
     * @return string
     */
    public function getTelefono()
    {
        return $this->container['telefono'];
    }

    /**
     * Sets telefono
     *
     * @param string $telefono telefono
     *
     * @return $this
     */
    public function setTelefono($telefono)
    {
        $this->container['telefono'] = $telefono;

        return $this;
    }

    /**
     * Gets resumen
     *
     * @return string
     */
    public function getResumen()
    {
        return $this->container['resumen'];
    }

    /**
     * Sets resumen
     *
     * @param string $resumen resumen
     *
     * @return $this
     */
    public function setResumen($resumen)
    {
        $this->container['resumen'] = $resumen;

        return $this;
    }

    /**
     * Gets nivel_educacional
     *
     * @return string
     */
    public function getNivelEducacional()
    {
        return $this->container['nivel_educacional'];
    }

    /**
     * Sets nivel_educacional
     *
     * @param string $nivel_educacional nivel_educacional
     *
     * @return $this
     */
    public function setNivelEducacional($nivel_educacional)
    {
        $allowedValues = $this->getNivelEducacionalAllowableValues();
        if (!is_null($nivel_educacional) && !in_array($nivel_educacional, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'nivel_educacional', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['nivel_educacional'] = $nivel_educacional;

        return $this;
    }

    /**
     * Gets titulo_carrera
     *
     * @return string
     */
    public function getTituloCarrera()
    {
        return $this->container['titulo_carrera'];
    }

    /**
     * Sets titulo_carrera
     *
     * @param string $titulo_carrera titulo_carrera
     *
     * @return $this
     */
    public function setTituloCarrera($titulo_carrera)
    {
        $this->container['titulo_carrera'] = $titulo_carrera;

        return $this;
    }

    /**
     * Gets anio_egreso
     *
     * @return int
     */
    public function getAnioEgreso()
    {
        return $this->container['anio_egreso'];
    }

    /**
     * Sets anio_egreso
     *
     * @param int $anio_egreso anio_egreso
     *
     * @return $this
     */
    public function setAnioEgreso($anio_egreso)
    {
        $this->container['anio_egreso'] = $anio_egreso;

        return $this;
    }

    /**
     * Gets anios_experiencia
     *
     * @return int
     */
    public function getAniosExperiencia()
    {
        return $this->container['anios_experiencia'];
    }

    /**
     * Sets anios_experiencia
     *
     * @param int $anios_experiencia anios_experiencia
     *
     * @return $this
     */
    public function setAniosExperiencia($anios_experiencia)
    {
        $this->container['anios_experiencia'] = $anios_experiencia;

        return $this;
    }

    /**
     * Gets areas_experiencia
     *
     * @return string[]
     */
    public function getAreasExperiencia()
    {
        return $this->container['areas_experiencia'];
    }

    /**
     * Sets areas_experiencia
     *
     * @param string[] $areas_experiencia areas_experiencia
     *
     * @return $this
     */
    public function setAreasExperiencia($areas_experiencia)
    {
        $this->container['areas_experiencia'] = $areas_experiencia;

        return $this;
    }

    /**
     * Gets competencias
     *
     * @return string[]
     */
    public function getCompetencias()
    {
        return $this->container['competencias'];
    }

    /**
     * Sets competencias
     *
     * @param string[] $competencias competencias
     *
     * @return $this
     */
    public function setCompetencias($competencias)
    {
        $this->container['competencias'] = $competencias;

        return $this;
    }

    /**
     * Gets rango_renta
     *
     * @return string
     */
    public function getRangoRenta()
    {
        return $this->container['rango_renta'];
    }

    /**
     * Sets rango_renta
     *
     * @param string $rango_renta rango_renta
     *
     * @return $this
     */
    public function setRangoRenta($rango_renta)
    {
        $this->container['rango_renta'] = $rango_renta;

        return $this;
    }

    /**
     * Gets tipo_jornada
     *
     * @return string
     */
    public function getTipoJornada()
    {
        return $this->container['tipo_jornada'];
    }

    /**
     * Sets tipo_jornada
     *
     * @param string $tipo_jornada tipo_jornada
     *
     * @return $this
     */
    public function setTipoJornada($tipo_jornada)
    {
        $allowedValues = $this->getTipoJornadaAllowableValues();
        if (!is_null($tipo_jornada) && !in_array($tipo_jornada, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'tipo_jornada', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['tipo_jornada'] = $tipo_jornada;

        return $this;
    }

    /**
     * Gets modalidad
     *
     * @return string
     */
    public function getModalidad()
    {
        return $this->container['modalidad'];
    }

    /**
     * Sets modalidad
     *
     * @param string $modalidad modalidad
     *
     * @return $this
     */
    public function setModalidad($modalidad)
    {
        $allowedValues = $this->getModalidadAllowableValues();
        if (!is_null($modalidad) && !in_array($modalidad, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'modalidad', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['modalidad'] = $modalidad;

        return $this;
    }

    /**
     * Gets persona_discapacidad
     *
     * @return bool
     */
    public function getPersonaDiscapacidad()
    {
        return $this->container['persona_discapacidad'];
    }

    /**
     * Sets persona_discapacidad
     *
     * @param bool $persona_discapacidad persona_discapacidad
     *
     * @return $this
     */
    public function setPersonaDiscapacidad($persona_discapacidad)
    {
        $this->container['persona_discapacidad'] = $persona_discapacidad;

        return $this;
    }

    /**
     * Gets portafolio_url
     *
     * @return string
     */
    public function getPortafolioUrl()
    {
        return $this->container['portafolio_url'];
    }

    /**
     * Sets portafolio_url
     *
     * @param string $portafolio_url portafolio_url
     *
     * @return $this
     */
    public function setPortafolioUrl($portafolio_url)
    {
        $this->container['portafolio_url'] = $portafolio_url;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
