<?php
/**
 * ContactoSolicitadoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ProviEmplea API
 *
 * API REST para la plataforma de empleo ProviEmplea de Providencia. Permite gestionar talentos, empresas y procesos de selección con curriculum ciego.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.81
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * ContactoSolicitadoTest Class Doc Comment
 *
 * @category    Class
 * @description Solicitud de contacto entre empresa y talento
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ContactoSolicitadoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ContactoSolicitado"
     */
    public function testContactoSolicitado()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "empresa_id"
     */
    public function testPropertyEmpresaId()
    {
    }

    /**
     * Test attribute "persona_id"
     */
    public function testPropertyPersonaId()
    {
    }

    /**
     * Test attribute "estado"
     */
    public function testPropertyEstado()
    {
    }

    /**
     * Test attribute "notas_admin"
     */
    public function testPropertyNotasAdmin()
    {
    }

    /**
     * Test attribute "fecha_contacto"
     */
    public function testPropertyFechaContacto()
    {
    }

    /**
     * Test attribute "fecha_entrevista"
     */
    public function testPropertyFechaEntrevista()
    {
    }

    /**
     * Test attribute "fecha_resultado"
     */
    public function testPropertyFechaResultado()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "empresa"
     */
    public function testPropertyEmpresa()
    {
    }

    /**
     * Test attribute "persona"
     */
    public function testPropertyPersona()
    {
    }
}
