<?php
/**
 * InlineResponse200Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ProviEmplea API
 *
 * API REST para la plataforma de empleo ProviEmplea de Providencia. Permite gestionar talentos, empresas y procesos de selección con curriculum ciego.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.81
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * InlineResponse200Test Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse200
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse200Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InlineResponse200"
     */
    public function testInlineResponse200()
    {
    }

    /**
     * Test attribute "total_personas"
     */
    public function testPropertyTotalPersonas()
    {
    }

    /**
     * Test attribute "personas_validadas"
     */
    public function testPropertyPersonasValidadas()
    {
    }

    /**
     * Test attribute "total_empresas"
     */
    public function testPropertyTotalEmpresas()
    {
    }

    /**
     * Test attribute "empresas_validadas"
     */
    public function testPropertyEmpresasValidadas()
    {
    }

    /**
     * Test attribute "contactos_pendientes"
     */
    public function testPropertyContactosPendientes()
    {
    }

    /**
     * Test attribute "contactos_en_proceso"
     */
    public function testPropertyContactosEnProceso()
    {
    }

    /**
     * Test attribute "contactos_exitosos"
     */
    public function testPropertyContactosExitosos()
    {
    }
}
