<?php
/**
 * PersonaCVCiegoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ProviEmplea API
 *
 * API REST para la plataforma de empleo ProviEmplea de Providencia. Permite gestionar talentos, empresas y procesos de selección con curriculum ciego.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.81
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * PersonaCVCiegoTest Class Doc Comment
 *
 * @category    Class
 * @description Vista pública del talento sin datos personales identificables
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PersonaCVCiegoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PersonaCVCiego"
     */
    public function testPersonaCVCiego()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "codigo_talento"
     */
    public function testPropertyCodigoTalento()
    {
    }

    /**
     * Test attribute "resumen"
     */
    public function testPropertyResumen()
    {
    }

    /**
     * Test attribute "nivel_educacional"
     */
    public function testPropertyNivelEducacional()
    {
    }

    /**
     * Test attribute "titulo_carrera"
     */
    public function testPropertyTituloCarrera()
    {
    }

    /**
     * Test attribute "anio_egreso"
     */
    public function testPropertyAnioEgreso()
    {
    }

    /**
     * Test attribute "anios_experiencia"
     */
    public function testPropertyAniosExperiencia()
    {
    }

    /**
     * Test attribute "tipo_jornada"
     */
    public function testPropertyTipoJornada()
    {
    }

    /**
     * Test attribute "modalidad"
     */
    public function testPropertyModalidad()
    {
    }

    /**
     * Test attribute "persona_discapacidad"
     */
    public function testPropertyPersonaDiscapacidad()
    {
    }
}
