<?php
/**
 * AdministracinApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ProviEmplea API
 *
 * API REST para la plataforma de empleo ProviEmplea de Providencia. Permite gestionar talentos, empresas y procesos de selección con curriculum ciego.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.81
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AdministracinApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AdministracinApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for actualizarEstadoContacto
     *
     * Actualizar estado de contacto.
     *
     */
    public function testActualizarEstadoContacto()
    {
    }

    /**
     * Test case for crearContactoSolicitado
     *
     * Registrar solicitud de contacto.
     *
     */
    public function testCrearContactoSolicitado()
    {
    }

    /**
     * Test case for getContactosSolicitados
     *
     * Listar contactos solicitados.
     *
     */
    public function testGetContactosSolicitados()
    {
    }

    /**
     * Test case for getEstadisticas
     *
     * Estadísticas generales de la plataforma.
     *
     */
    public function testGetEstadisticas()
    {
    }
}
